{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:      {{ .Values.serviceAccount.name | default (include "nodejs-app.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:    {{ include "nodejs-app.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}