{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:      {{ include "nodejs-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "nodejs-app.labels" . | nindent 4 }}
    release: kube-prometheus-stack   # Must match Prometheus operator selector
spec:
  selector:
    matchLabels: {{ include "nodejs-app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port:     http
      path:     {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scheme:   http
{{- end }}